language: android
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-21

android:
  components:
    - build-tools-21.0.3
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

script: ./gradlew connectedAndroidTest
